### ISSUE TITLE
/dev/video1: No such file or directory

### ISSUE THREAD

**Issue by dfbills** [brutella/hkcam#20]
After getting everything working 100% again, I started tinkering around with the core Pi software and somehow managed to break it again.  After expanding my disk size in raspi-config, I know that I: updated the locale, WiFi frequencies, time zone, cleared apt update files, updated Pi firmware, and renamed the host back to raspberrypi.local from raspberrypi-2.local.

Log files show obvious error of:

/dev/video1: No such file or directory

Checking the devices, I see:

video0
video10
video11
video12

But, obviously no video1.  Not sure how to re-assign device IDs 

Raw log:

pi@raspberrypi:/var/log/hkcam $ vcgencmd get_camera
supported=1 detected=1
pi@raspberrypi:/var/log/hkcam $ tail -f current 
2019-06-01_20:12:47.95427   libavcodec     57. 64.101 / 57. 64.101
2019-06-01_20:12:47.95448   libavformat    57. 56.101 / 57. 56.101
2019-06-01_20:12:47.95467   libavdevice    57.  1.100 / 57.  1.100
2019-06-01_20:12:47.95487   libavfilter     6. 65.100 /  6. 65.100
2019-06-01_20:12:47.95528   libavresample   3.  1.  0 /  3.  1.  0
2019-06-01_20:12:47.95553   libswscale      4.  2.100 /  4.  2.100
2019-06-01_20:12:47.95574   libswresample   2.  3.100 /  2.  3.100
2019-06-01_20:12:47.95593   libpostproc    54.  1.100 / 54.  1.100
2019-06-01_20:12:47.99827 [video4linux2,v4l2 @ 0x1cfa310] Cannot open video device /dev/video1: No such file or directory
2019-06-01_20:12:47.99890 /dev/video1: No such file or directory
2019-06-01_20:12:54.66859 DEBUG 2019/06/01 16:12:54 resource.go:43: [2604:2000:1483:4ee:9540:20e7:836f:7841]:49162 POST /resource
2019-06-01_20:12:56.13406 ffmpeg version 3.2.14-1~deb9u1+rpt1 Copyright (c) 2000-2019 the FFmpeg developers
2019-06-01_20:12:56.13542   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
2019-06-01_20:12:56.13626   configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
2019-06-01_20:12:56.13944   libavutil      55. 34.101 / 55. 34.101
2019-06-01_20:12:56.14053   libavcodec     57. 64.101 / 57. 64.101
2019-06-01_20:12:56.14159   libavformat    57. 56.101 / 57. 56.101
2019-06-01_20:12:56.14281   libavdevice    57.  1.100 / 57.  1.100
2019-06-01_20:12:56.14389   libavfilter     6. 65.100 /  6. 65.100
2019-06-01_20:12:56.14663   libavresample   3.  1.  0 /  3.  1.  0
2019-06-01_20:12:56.14836   libswscale      4.  2.100 /  4.  2.100
2019-06-01_20:12:56.14945   libswresample   2.  3.100 /  2.  3.100
2019-06-01_20:12:56.15053   libpostproc    54.  1.100 / 54.  1.100
2019-06-01_20:12:56.16087 [video4linux2,v4l2 @ 0x9101e0] Cannot open video device /dev/video1: No such file or directory
2019-06-01_20:12:56.16240 /dev/video1: No such file or directory
2019-06-01_20:12:56.19036 DEBUG 2019/06/01 16:12:56 ffmpeg.go:181: Active sesssions map[E??;Mͦ???b8?:0x14b2500]
2019-06-01_20:12:56.19139 INFO 2019/06/01 16:12:56 resource.go:45: r.imgFn() exit status 1
2019-06-01_20:13:06.26429 DEBUG 2019/06/01 16:13:06 resource.go:43: [2604:2000:1483:4ee:9540:20e7:836f:7841]:49162 POST /resource
2019-06-01_20:13:07.72437 ffmpeg version 3.2.14-1~deb9u1+rpt1 Copyright (c) 2000-2019 the FFmpeg developers
2019-06-01_20:13:07.72576   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
2019-06-01_20:13:07.72659   configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
2019-06-01_20:13:07.72987   libavutil      55. 34.101 / 55. 34.101
2019-06-01_20:13:07.73099   libavcodec     57. 64.101 / 57. 64.101
2019-06-01_20:13:07.73207   libavformat    57. 56.101 / 57. 56.101
2019-06-01_20:13:07.73366   libavdevice    57.  1.100 / 57.  1.100
2019-06-01_20:13:07.73600   libavfilter     6. 65.100 /  6. 65.100
2019-06-01_20:13:07.73708   libavresample   3.  1.  0 /  3.  1.  0
2019-06-01_20:13:07.73816   libswscale      4.  2.100 /  4.  2.100
2019-06-01_20:13:07.74082   libswresample   2.  3.100 /  2.  3.100
2019-06-01_20:13:07.74401   libpostproc    54.  1.100 / 54.  1.100
2019-06-01_20:13:07.75213 [video4linux2,v4l2 @ 0xdf71e0] Cannot open video device /dev/video1: No such file or directory
2019-06-01_20:13:07.75419 /dev/video1: No such file or directory
2019-06-01_20:13:07.78219 DEBUG 2019/06/01 16:13:07 ffmpeg.go:181: Active sesssions map[E??;Mͦ???b8?:0x14b2500]
2019-06-01_20:13:07.78323 INFO 2019/06/01 16:13:07 resource.go:45: r.imgFn() exit status 1
2019-06-01_20:13:14.75006 DEBUG 2019/06/01 16:13:14 characteristics.go:48: [2604:2000:1483:4ee:9540:20e7:836f:7841]:49162 PUT /characteristics
2019-06-01_20:13:14.75258 DEBUG 2019/06/01 16:13:14 characteristic_controller.go:76: {"characteristics":[{"aid":1,"iid":18,"value":"ARUCAQABEEWM5ok7EU3NpskZP7xiOLQ="}]}
2019-06-01_20:13:14.75868 DEBUG 2019/06/01 16:13:14 setup.go:53: {Command:{Identifier:[69 140 230 137 59 17 77 205 166 201 25 63 188 98 56 180] Type:0} Video:{CodecType:0 CodecParams:{Profiles:[] Levels:[] Packetizations:[]} Attributes:{Width:0 Height:0 Framerate:0} RTP:{PayloadType:0 Ssrc:0 Bitrate:0 Interval:0 ComfortNoisePayloadType:0 MTU:0}} Audio:{CodecType:0 CodecParams:{Channels:0 Bitrate:0 Samplerate:0} RTP:{PayloadType:0 Ssrc:0 Bitrate:0 Interval:0 ComfortNoisePayloadType:0 MTU:0} ComfortNoise:false}}
2019-06-01_20:13:14.76144 DEBUG 2019/06/01 16:13:14 stream.go:28: stop stream
2019-06-01_20:13:14.76376 DEBUG 2019/06/01 16:13:14 ffmpeg.go:113: Stopping loopback
2019-06-01_20:13:17.81144 DEBUG 2019/06/01 16:13:17 resource.go:43: [2604:2000:1483:4ee:9540:20e7:836f:7841]:49162 POST /resource
2019-06-01_20:13:19.78472 ffmpeg version 3.2.14-1~deb9u1+rpt1 Copyright (c) 2000-2019 the FFmpeg developers
2019-06-01_20:13:19.79914   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
2019-06-01_20:13:19.80006   configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
2019-06-01_20:13:19.80183   libavutil      55. 34.101 / 55. 34.101
2019-06-01_20:13:19.80329   libavcodec     57. 64.101 / 57. 64.101
2019-06-01_20:13:19.80417   libavformat    57. 56.101 / 57. 56.101
2019-06-01_20:13:19.80503   libavdevice    57.  1.100 / 57.  1.100
2019-06-01_20:13:19.80602   libavfilter     6. 65.100 /  6. 65.100
2019-06-01_20:13:19.80689   libavresample   3.  1.  0 /  3.  1.  0
2019-06-01_20:13:19.80780   libswscale      4.  2.100 /  4.  2.100
2019-06-01_20:13:19.80868   libswresample   2.  3.100 /  2.  3.100
2019-06-01_20:13:19.81025   libpostproc    54.  1.100 / 54.  1.100
2019-06-01_20:13:20.57459 Input #0, video4linux2,v4l2, from '/dev/video0':
2019-06-01_20:13:20.57895   Duration: N/A, start: 771.007976, bitrate: 283115 kb/s
2019-06-01_20:13:20.58114     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1024x768, 283115 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
2019-06-01_20:13:20.58485 [v4l2 @ 0x69e010] Unable to open V4L2 device '/dev/video1'
2019-06-01_20:13:20.59651 Could not write header for output file #0 (incorrect codec parameters ?): No such file or directoryStream mapping:
2019-06-01_20:13:20.59775   Stream #0:0 -> #0:0 (copy)
2019-06-01_20:13:20.75031     Last message repeated 1 times
2019-06-01_20:13:20.99638 ffmpeg version 3.2.14-1~deb9u1+rpt1 Copyright (c) 2000-2019 the FFmpeg developers
2019-06-01_20:13:20.99766   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
2019-06-01_20:13:20.99847   configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
2019-06-01_20:13:21.00183   libavutil      55. 34.101 / 55. 34.101
2019-06-01_20:13:21.00295   libavcodec     57. 64.101 / 57. 64.101
2019-06-01_20:13:21.00402   libavformat    57. 56.101 / 57. 56.101
2019-06-01_20:13:21.00517   libavdevice    57.  1.100 / 57.  1.100
2019-06-01_20:13:21.00628   libavfilter     6. 65.100 /  6. 65.100
2019-06-01_20:13:21.00736   libavresample   3.  1.  0 /  3.  1.  0
2019-06-01_20:13:21.00844   libswscale      4.  2.100 /  4.  2.100
2019-06-01_20:13:21.00951   libswresample   2.  3.100 /  2.  3.100
2019-06-01_20:13:21.01059   libpostproc    54.  1.100 / 54.  1.100
2019-06-01_20:13:21.01751 [video4linux2,v4l2 @ 0x145b1e0] Cannot open video device /dev/video1: No such file or directory
2019-06-01_20:13:21.01907 /dev/video1: No such file or directory
2019-06-01_20:13:21.04581 DEBUG 2019/06/01 16:13:21 ffmpeg.go:186: Stopping loopback
2019-06-01_20:13:21.04655 INFO 2019/06/01 16:13:21 resource.go:45: r.imgFn() exit status 1
^C

**Comment by brutella** [comment]
`/dev/video1` is created by the v4l2loopback kernel extension and is needed to allow multiple access to the camera stream.

If `/dev/video1` is not available, please verify that the camera is correctly connected to the RPi as shown in the [wiki](https://github.com/brutella/hkcam/wiki/Common-Issues).

**Comment by xd94402002** [comment]
I have the exact same issue with both my v2 v1 pi camera 
I’m sure that the camera is connected to the RPi 
It is able to see video and take picture with the “raspistill -o image.png” command

**Comment by brutella** [comment]
@xd94402002 Did you install the pre-configured Raspbian image or just installed the hkcam binary?

**Comment by xd94402002** [comment]
I installed on my pi3 through playbook 
I found that it doesn’t install the v4l2loopback module 
After manually install v4l2loopback the cam start streaming

**Comment by xd94402002** [comment]
Additionally,the FPS just 5. Is that the performance limit on rpi ? The average cpu usage is under 5%. It seem like it doesn’t make full use of the resources.

**Comment by AndreaCCIE** [comment]
I've got the same /dev/video1 error, the camera cable wasn't plugged correctly.

**Comment by benbeton** [comment]
I facing the same issue. camera is plugged in correctly. I'm using the provided Image 0.0.8.
I guess it happened after I expanded the disk

**Comment by dfbills** [comment]
@benbeton - I also expanded my disk as I'm running on a 64GB card.  I haven't had a chance to rebuild from scratch yet.

**Comment by beckmx** [comment]
hello @brutella I have the same problem with these specs:
- raspi 3
- suggeted image on 8gig sd
- raspi cam 1.3 well connected

I could connect it to wifi and ssh, I also could add the camera in “Home” but no image is shown. Then I connected another USB camera and that one did create the video1 and could stream from there, but the raspi cam seems to fail to work.

**Comment by AndreaCCIE** [comment]
So, a quick update. I've got this error a couple of times on a working camera after the reboot.
The solution I found was to kill the hkcam processes:

`pi@raspicam:~ ps aux | grep hkcam
root       558  0.0  0.0   1684   364 ?        Ss   14:15   0:00 runsv hkcam
root       564  0.0  0.0   1828   324 ?        S    14:15   0:00 svlogd -tt /var/log/hkcam
root       565  0.7  1.3 801948 10256 ?        Sl   14:15   0:00 hkcam --min_video_bitrate=2048 --data_dir=/var/lib/hkcam/data --verbose=true
pi         736  0.0  0.0   3492   396 pts/1    S+   14:17   0:00 tail -f /var/log/hkcam/current
pi         742  0.0  0.0   4368   536 pts/0    S+   14:17   0:00 grep --color=auto hkcam
pi@raspicam:~ sudo kill -9 558 564 565`

hkcam will restart by itself and the error disappeared

**Comment by beckmx** [comment]
after killing the processes, did u rerun again the process?

**Comment by AndreaCCIE** [comment]
No, it restarts by itself. But now I have to do it after each reboot. It looks like a wrong order of operations.

**Comment by pleasantone** [comment]
I'm seeing the same thing, and `raspistill` gets the image just fine. I -also- did a disk expansion followed by an apt-get update/dist-upgrade. I suspect the loopback module is not being loaded properly in the kernel.

```
root@picam1:/var/log/hkcam# lsmod
Module                  Size  Used by
bnep                   12862  2
hci_uart               30428  1
btbcm                   7822  1 hci_uart
serdev                 11024  1 hci_uart
bluetooth             397237  24 hci_uart,bnep,btbcm
ecdh_generic           19994  1 bluetooth
brcmfmac              280034  0
brcmutil                9617  1 brcmfmac
sha256_generic         10778  0
cfg80211              596656  1 brcmfmac
raspberrypi_hwmon       2959  0
snd_bcm2835            16839  0
hwmon                  11200  1 raspberrypi_hwmon
snd_pcm                92916  1 snd_bcm2835
snd_timer              23433  1 snd_pcm
snd                    63223  3 snd_timer,snd_bcm2835,snd_pcm
rfkill                 22462  6 bluetooth,cfg80211
bcm2835_codec          28300  0
v4l2_mem2mem           18877  1 bcm2835_codec
videobuf2_dma_contig    10303  1 bcm2835_codec
uio_pdrv_genirq         3953  0
uio                    11360  1 uio_pdrv_genirq
fixed                   3336  0
bcm2835_v4l2           35910  0
bcm2835_mmal_vchiq     20644  2 bcm2835_codec,bcm2835_v4l2
vc_sm_cma              25091  1 bcm2835_mmal_vchiq
v4l2_common             7385  1 bcm2835_v4l2
videobuf2_vmalloc       6084  1 bcm2835_v4l2
videobuf2_memops        1973  2 videobuf2_dma_contig,videobuf2_vmalloc
videobuf2_v4l2         16373  3 bcm2835_codec,bcm2835_v4l2,v4l2_mem2mem
videobuf2_common       37369  4 bcm2835_codec,bcm2835_v4l2,v4l2_mem2mem,videobuf2_v4l2
videodev              182757  6 bcm2835_codec,v4l2_common,videobuf2_common,bcm2835_v4l2,v4l2_mem2mem,videobuf2_v4l2
media                  27597  2 videodev,v4l2_mem2mem
ip_tables              13419  0
x_tables               24457  1 ip_tables
ipv6                  429149  40
```

Who is responsible for BUILDING it, as it's not present in the newer kernel:

```
root@picam1:/lib/modules# find . -name v4*
./4.19.57-v7+/kernel/drivers/media/v4l2-core
./4.19.57-v7+/kernel/drivers/media/v4l2-core/v4l2-fwnode.ko
./4.19.57-v7+/kernel/drivers/media/v4l2-core/v4l2-common.ko
./4.19.57-v7+/kernel/drivers/media/v4l2-core/v4l2-mem2mem.ko
./4.19.57-v7+/kernel/drivers/media/v4l2-core/v4l2-dv-timings.ko
./4.19.42+/extra/v4l2loopback.ko.    <--------
./4.19.57+/kernel/drivers/media/v4l2-core
./4.19.57+/kernel/drivers/media/v4l2-core/v4l2-fwnode.ko
./4.19.57+/kernel/drivers/media/v4l2-core/v4l2-common.ko
./4.19.57+/kernel/drivers/media/v4l2-core/v4l2-mem2mem.ko
./4.19.57+/kernel/drivers/media/v4l2-core/v4l2-dv-timings.ko
root@picam1:/lib/modules# modprobe v4l2loopback
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/4.19.57+
```

**Comment by pleasantone** [comment]
Unfortunately, building the module fails because of -W flags...

```
root@picam1:/lib/modules# apt-get install v4l2loopback-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  dkms
Suggested packages:
  python3-apport menu v4l2loopback-utils
The following NEW packages will be installed:
  dkms v4l2loopback-dkms
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 107 kB of archives.
After this operation, 397 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://mirror.pit.teraswitch.com/raspbian/raspbian stretch/main armhf dkms all 2.3-2 [74.8 kB]
Get:2 http://mirror.pit.teraswitch.com/raspbian/raspbian stretch/main armhf v4l2loopback-dkms all 0.10.0-1 [32.6 kB]
Fetched 107 kB in 1s (95.3 kB/s)
Selecting previously unselected package dkms.
(Reading database ... 69697 files and directories currently installed.)
Preparing to unpack .../archives/dkms_2.3-2_all.deb ...
Unpacking dkms (2.3-2) ...
Selecting previously unselected package v4l2loopback-dkms.
Preparing to unpack .../v4l2loopback-dkms_0.10.0-1_all.deb ...
Unpacking v4l2loopback-dkms (0.10.0-1) ...
Setting up dkms (2.3-2) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up v4l2loopback-dkms (0.10.0-1) ...
Loading new v4l2loopback-0.10.0 DKMS files...
It is likely that 4.19.57+ belongs to a chroot's host
Building for 4.19.42+, 4.19.57+ and 4.19.57-v7+
Module build for kernel 4.19.42+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 4.19.57+
Error! Bad return status for module build on kernel: 4.19.57+ (armv6l)
Consult /var/lib/dkms/v4l2loopback/0.10.0/build/make.log for more information.
root@picam1:/lib/modules# cat /var/lib/dkms/v4l2loopback/0.10.0/build/make.log
DKMS make.log for v4l2loopback-0.10.0 for kernel 4.19.57+ (armv6l)
Tue 16 Jul 00:58:07 BST 2019
Building v4l2-loopback driver...
make -C /lib/modules/4.19.57+/build M=/var/lib/dkms/v4l2loopback/0.10.0/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.57+'
  CC [M]  /var/lib/dkms/v4l2loopback/0.10.0/build/v4l2loopback.o
/var/lib/dkms/v4l2loopback/0.10.0/build/v4l2loopback.c: In function ‘v4l2_loopback_init’:
/var/lib/dkms/v4l2loopback/0.10.0/build/v4l2loopback.c:2206:2: error: implicit declaration of function ‘setup_timer’ [-Werror=implicit-function-declaration]
  setup_timer(&dev->sustain_timer, sustain_timer_clb, nr);
  ^~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:309: recipe for target '/var/lib/dkms/v4l2loopback/0.10.0/build/v4l2loopback.o' failed
make[2]: *** [/var/lib/dkms/v4l2loopback/0.10.0/build/v4l2loopback.o] Error 1
Makefile:1517: recipe for target '_module_/var/lib/dkms/v4l2loopback/0.10.0/build' failed
make[1]: *** [_module_/var/lib/dkms/v4l2loopback/0.10.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.57+'
Makefile:42: recipe for target 'v4l2loopback.ko' failed
make: *** [v4l2loopback.ko] Error 2
```

**Comment by pleasantone** [comment]
Sorry to keep polluting this stream, but v4l2loopback-dkms fails because setup_timer() is a deprecated kernel timer mechanism that was updated to a new paradigm (timer_setup() in 4.14). I have no idea why the loopback module is working in the base distribution (4.19.42) and fails in 4.19.57, but I suspect some compatibly macro was removed (which should never have happened in a point release).

**Comment by Keesromkes** [comment]
> After manually install v4l2loopback the cam start streaming

Did this as well (on top of apt-get upgrade/update, and expanding my SD card) and that brought the camera back to life. Pretty much what @pleasantone said here.

**Comment by brutella** [comment]
Yeah, getting the v4l2loopback kernel extension working is no fun.

**Comment by Velkas** [comment]
@pleasantone Is there any chance you could detail your fix a little more? 

I flashed my Pi Zero W with the latest pre-built from this repo. Added Wifi and SSH to remote manage it. After first boot, I expanded the filesystem and ran apt-get update/upgrade.

I wound up with OP's problem but I'm having trouble following your repair steps. I've never used ansible and after installing it on the Pi and copying over the ansible folder-- it fails to run.

**Comment by hannesbhm** [comment]
Hello! I get the following error:

pi@raspberrypi:~ $ cd /dev/video99
-bash: cd: /dev/video99: No such file or directory

Im sure that i did every step right and can open the cam via homekit but without pictures. The camera doesn't answer.

Maybe someone can help me. Thanks!
